[project]
name = "edithing-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django-ninja>=1.4.3",
    "django-stubs[compatible-mypy]>=5.2.1",
    "mypy>=1.16.1",
]

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
python_version = "3.13"
strict = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_any_generics = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unreachable = true
strict_equality = true
exclude = [
    "manage.py",
    "migrations/",
    ".venv/",
    "venv/",
]

# Less strict checking for Django settings
[[tool.mypy.overrides]]
module = "web.settings"
ignore_errors = true

# Less strict for Django generated files
[[tool.mypy.overrides]]
module = [
    "web.wsgi",
    "web.asgi",
]
disallow_untyped_defs = false

[tool.django-stubs]
django_settings_module = "web.settings"