"""
Django settings for mechlaw project.

Generated by 'django-admin startproject' using Django 1.10.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Add `lagasafn` to the path.
sys.path.append("..")


# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "bill",
    "core",
    "law",
    "advert",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.middleware.OpenAPIFixMiddleware",
]

ROOT_URLCONF = "mechlaw.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.contextprocessors.globals",
            ],
        },
    },
]

WSGI_APPLICATION = "mechlaw.wsgi.application"


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Locale configuration
LANGUAGES = (("is", "Icelandic"),)
LOCALE_PATHS = ("locale",)
LANGUAGE_CODE = 'is'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Options are: ['is']
LEGAL_FRAMEWORK = 'is'


# Where to find the XML data.
DATA_DIR = os.path.join(BASE_DIR, '..', 'data', 'xml')


# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")


# External URLs.
EDITOR_URL = "https://frumvarp.althingi.net/law/%s.%s"


# Cache.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": os.path.join(
            BASE_DIR, ".data-cache"
        ),  # Set an appropriate directory
        "TIMEOUT": 300,  # Default timeout (in seconds)
        "OPTIONS": {"MAX_ENTRIES": 1000},  # Limit number of cached items
    }
}


CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]


# Load configurable settings.
from mechlaw.local_settings import *


# Read constants.
from mechlaw.constants import *
