apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: {{ .Release.Namespace }}
data:
  ALLOWED_HOSTS: {{ .Values.host }}
  VITE_SERVER_BASE_URL: https://{{ .Values.host }}
  BASE_PATH: {{ .Values.basePath }}

